# Configuration file for data extraction targets and directories
# Commented lines indicate potential future targets that can be activated as needed, for development purposes now they are disabled.
extract_targets:
  commodities:
    - WTI
    - BRENT
    # - COFFEE
    # - SUGAR
    # - COPPER
    # - NATURAL_GAS
    # - ALUMINUM

  currency_pairs:
    - [USD, EUR]
    - [USD, JPY]
    # - [GBP, USD]
    # - [BRL, USD]
    # - [GBP, JPY]

  stock_symbols:
    - AAPL
    - GOOGL
    - AMZN
    # - NVDA
    # - META
    # - AMD
    # - IBM
    
  outputsize: full

  crypto_pairs:
    - [BTC, USD]
    - [ETH, USD]
    # - [LTC, USD]
    # - [XRP, USD]
    # - [ADA, USD]
    # - [DOGE, USD]

  forex_pairs:
    - [BRL, USD]
    - [EUR, USD]
    # - [GBP, USD]
    # - [JPY, USD]
    # - [CAD, USD]
    # - [CNY, USD]

data_directory: 
  raw_data: ./artifacts/raw/
  processed_data: ./artifacts/processed/

database_schemas:
  - finance